=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-microsoft-sql-server-extension/conf/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hivemq-microsoft-sql-server-extension" type="configEntity">
        <xs:key name="mssql-id">
            <xs:selector xpath="mssqls/mssql"/>
            <xs:field xpath="id"/>
        </xs:key>
        <xs:keyref name="mqtt-to-mssql-id-ref" refer="mssql-id">
            <xs:selector xpath="mqtt-to-mssql-routes/mqtt-to-mssql-route"/>
            <xs:field xpath="mssql-id"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="configEntity">
        <xs:all>
            <xs:element name="internal" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="option" type="InternalOptionEntity" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="mssqls">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mssql" type="MssqlEntity" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="mqtt-to-mssql-routes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mqtt-to-mssql-route" type="MqttToMssqlRouteEntity"
                                    maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="InternalOptionEntity">
        <xs:all>
            <xs:element name="key" type="nonEmptyString"/>
            <xs:element name="value" type="nonEmptyString"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="MssqlEntity">
        <xs:all>
            <xs:element name="id" type="lowercaseId"/>
            <xs:element name="server-name" type="nonEmptyString"/>
            <xs:element name="port" type="xs:nonNegativeInteger"/>
            <xs:element name="database" type="nonEmptyString"/>
            <xs:element name="authentication" type="AuthenticationEntity"/>
            <xs:element name="tls" type="TlsEntity" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="MqttToMssqlRouteEntity">
        <xs:all>
            <xs:element name="id" type="lowercaseId"/>
            <xs:element name="mssql-id" type="xs:IDREF"/>
            <xs:element name="enabled" type="xs:boolean" minOccurs="0"/>
            <xs:element name="mqtt-topic-filters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mqtt-topic-filter" type="nonEmptyString" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="processor">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="insert-statement">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element name="table" type="nonEmptyString"/>
                                    <xs:element name="use-bulk-copy" type="xs:boolean" minOccurs="0"/>
                                    <xs:element name="columns">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="column" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:all>
                                                            <xs:element name="name" type="nonEmptyString"/>
                                                            <xs:element name="value" type="columnValueEntity"/>
                                                        </xs:all>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="AuthenticationEntity">
        <xs:choice>
            <xs:element name="basic" type="BasicAuthenticationEntity"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="BasicAuthenticationEntity">
        <xs:all>
            <xs:element name="username" type="nonEmptyString"/>
            <xs:element name="password" type="nonEmptyString"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="TlsEntity">
        <xs:all>
            <xs:element name="enabled" type="xs:boolean" default="true" minOccurs="0"/>
            <xs:element name="truststore" type="TruststoreEntity" minOccurs="0"/>
            <xs:element name="trust-server-certificate" type="xs:boolean" default="true" minOccurs="0"/>
            <xs:element name="host-name-in-certificate" type="nonEmptyString" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="TruststoreEntity">
        <xs:all>
            <xs:element name="path" type="nonEmptyString"/>
            <xs:element name="password" type="nonEmptyString"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="columnValueEntity">
        <xs:union memberTypes="allowedPlaceholdersEnum allowedPlaceholdersPattern"/>
    </xs:simpleType>

    <xs:simpleType name="allowedPlaceholdersEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mqtt-topic"/>
            <xs:enumeration value="mqtt-payload-utf8"/>
            <xs:enumeration value="mqtt-payload-base64"/>
            <xs:enumeration value="mqtt-qos"/>
            <xs:enumeration value="mqtt-retain"/>
            <xs:enumeration value="mqtt-packet-id"/>
            <xs:enumeration value="mqtt-payload-format-indicator"/>
            <xs:enumeration value="mqtt-response-topic"/>
            <xs:enumeration value="mqtt-correlation-data-utf8"/>
            <xs:enumeration value="mqtt-correlation-data-base64"/>
            <xs:enumeration value="mqtt-user-properties-json"/>
            <xs:enumeration value="timestamp-ms"/>
            <xs:enumeration value="timestamp-iso-8601"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="allowedPlaceholdersPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="mqtt-user-properties\$.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lowercaseId">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-z0-9_\-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-microsoft-sql-server-extension/conf/examples/config.xml
<hivemq-microsoft-sql-server-extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:noNamespaceSchemaLocation="config.xsd">
    <mssqls>
        <mssql>
            <id>my-mssql-id</id>
            <server-name>my.host.com</server-name>
            <port>1433</port>
            <database>my-database</database>
            <authentication>
                <basic>
                    <username>my-user</username>
                    <password>my-password</password>
                </basic>
            </authentication>
        </mssql>
    </mssqls>

    <mqtt-to-mssql-routes>
        <mqtt-to-mssql-route>
            <id>my-mqtt-to-mssql-route-insert</id>
            <mssql-id>my-mssql-id</mssql-id>
            <mqtt-topic-filters>
                <mqtt-topic-filter>#</mqtt-topic-filter>
            </mqtt-topic-filters>
            <processor>
                <insert-statement>
                    <table>mqtt_to_mssql_table</table>
                    <use-bulk-copy>true</use-bulk-copy>
                    <columns>
                        <column>
                            <name>topic</name>
                            <value>mqtt-topic</value>
                        </column>
                        <column>
                            <name>payload_utf8</name>
                            <value>mqtt-payload-utf8</value>
                        </column>
                    </columns>
                </insert-statement>
            </processor>
        </mqtt-to-mssql-route>
    </mqtt-to-mssql-routes>
</hivemq-microsoft-sql-server-extension>
