=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-mysql-extension/conf/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="hivemq-mysql-extension" type="configEntity"/>

    <xs:complexType name="configEntity">
        <xs:all>
            <xs:element name="internal" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="option" type="InternalOptionEntity" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="mysqls">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mysql" type="MysqlsEntity" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="mqtt-to-mysql-routes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mqtt-to-mysql-route" type="MqttToMysqlRouteEntity"
                                    maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="InternalOptionEntity">
        <xs:all>
            <xs:element name="key" type="nonEmptyString"/>
            <xs:element name="value" type="nonEmptyString"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="MysqlsEntity">
        <xs:all>
            <xs:element name="id" type="lowercaseId"/>
            <xs:element name="host" type="nonEmptyString"/>
            <xs:element name="port" type="xs:nonNegativeInteger"/>
            <xs:element name="database" type="nonEmptyString"/>
            <xs:element name="username" type="nonEmptyString"/>
            <xs:element name="password" type="nonEmptyString"/>
            <xs:element name="tls" minOccurs="0">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="enabled" type="xs:boolean" minOccurs="0"/>
                        <xs:element name="root-certificate" type="nonEmptyString" minOccurs="0"/>
                        <xs:element name="client-certificate" type="nonEmptyString" minOccurs="0"/>
                        <xs:element name="client-private-key" type="nonEmptyString" minOccurs="0"/>
                        <xs:element name="verify-hostname" type="xs:boolean" minOccurs="0"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="MqttToMysqlRouteEntity">
        <xs:all>
            <xs:element name="id" type="lowercaseId"/>
            <xs:element name="mysql-id" type="xs:IDREF"/>
            <xs:element name="enabled" type="xs:boolean" minOccurs="0"/>
            <xs:element name="mqtt-topic-filters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mqtt-topic-filter" type="nonEmptyString" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="processor">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="statement-template" type="nonEmptyString"/>
                        <xs:element name="insert-statement">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element name="table" type="nonEmptyString"/>
                                    <xs:element name="batching" type="xs:boolean" minOccurs="0"/>
                                    <xs:element name="columns">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="column" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:all>
                                                            <xs:element name="name" type="nonEmptyString"/>
                                                            <xs:element name="value" type="columnValueEntity"/>
                                                        </xs:all>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="columnValueEntity">
        <xs:union memberTypes="allowedPlaceholdersEnum allowedPlaceholdersPattern"/>
    </xs:simpleType>

    <xs:simpleType name="allowedPlaceholdersEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mqtt-topic"/>
            <xs:enumeration value="mqtt-payload-utf8"/>
            <xs:enumeration value="mqtt-payload-base64"/>
            <xs:enumeration value="mqtt-qos"/>
            <xs:enumeration value="mqtt-retain"/>
            <xs:enumeration value="mqtt-packet-id"/>
            <xs:enumeration value="mqtt-payload-format-indicator"/>
            <xs:enumeration value="mqtt-response-topic"/>
            <xs:enumeration value="mqtt-correlation-data-utf8"/>
            <xs:enumeration value="mqtt-correlation-data-base64"/>
            <xs:enumeration value="mqtt-user-properties-json"/>
            <xs:enumeration value="timestamp-ms"/>
            <xs:enumeration value="timestamp-iso-8601"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="allowedPlaceholdersPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="mqtt-user-properties\$.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lowercaseId">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-z0-9_\-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-mysql-extension/conf/examples/config.xml
<hivemq-mysql-extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:noNamespaceSchemaLocation="config.xsd">
    <mysqls>
        <mysql>
            <id>my-mysql-id</id>
            <host>my.host.com</host>
            <port>3306</port>
            <database>my-database</database>
            <username>my-user</username>
            <password>my-password</password>
        </mysql>
    </mysqls>

    <mqtt-to-mysql-routes>

        <!-- insert every message using the INSERT STATEMENT processor -->
        <mqtt-to-mysql-route>
            <id>my-mqtt-to-mysql-route-insert</id>
            <mysql-id>my-mysql-id</mysql-id>
            <mqtt-topic-filters>
                <mqtt-topic-filter>#</mqtt-topic-filter>
            </mqtt-topic-filters>
            <processor>
                <insert-statement>
                    <table>mqtt_to_mysql_table</table>
                    <batching>true</batching>
                    <columns>
                        <column>
                            <name>topic</name>
                            <value>mqtt-topic</value>
                        </column>
                        <column>
                            <name>payload_utf8</name>
                            <value>mqtt-payload-utf8</value>
                        </column>
                    </columns>
                </insert-statement>
            </processor>
        </mqtt-to-mysql-route>

        <!-- insert every message using the STATEMENT TEMPLATE processor -->
        <mqtt-to-mysql-route>
            <id>my-mqtt-to-mysql-route-template</id>
            <mysql-id>my-mysql-id</mysql-id>
            <mqtt-topic-filters>
                <mqtt-topic-filter>#</mqtt-topic-filter>
            </mqtt-topic-filters>
            <processor>
                <statement-template>statement-template.sql</statement-template>
            </processor>
        </mqtt-to-mysql-route>

    </mqtt-to-mysql-routes>
</hivemq-mysql-extension>
