=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-bridge-extension/conf/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="authentication" type="authenticationEntity"/>

    <xs:element name="bridge" type="bridgeEntity"/>

    <xs:element name="bridges" type="bridgesEntity"/>

    <xs:element name="cipher-suites" type="cipherSuitesEntity"/>

    <xs:element name="connection" type="connectionEntity"/>

    <xs:element name="excludes" type="excludedFiltersEntity"/>

    <xs:element name="hivemq-bridge-extension" type="extensionEntity"/>

    <xs:element name="internal" nillable="true" type="xs:anyType"/>

    <xs:element name="keystore" type="keystoreEntity"/>

    <xs:element name="message-log" type="messageLogEntity"/>

    <xs:element name="mqtt" type="mqttEntity"/>

    <xs:element name="mqtt-simple-authentication" type="mqttSimpleAuthenticationEntity"/>

    <xs:element name="option" type="optionEntity"/>

    <xs:element name="protocols" type="protocolsEntity"/>

    <xs:element name="remote-broker" type="remoteBrokerEntity"/>

    <xs:element name="static" type="staticConnectionEntity"/>

    <xs:element name="tls" type="tlsEntity"/>

    <xs:element name="flow-control" type="flowControlEntity"/>

    <xs:element name="loop-prevention" type="loopPreventionEntity"/>

    <xs:element name="topic" type="topicEntity"/>

    <xs:element name="topics" type="topicsEntity"/>

    <xs:element name="truststore" type="truststoreEntity"/>

    <xs:element name="websocket" type="websocketEntity"/>

    <xs:element name="hmq-hop-count-removal" type="hopCountRemovalEntity"/>

    <xs:element name="excluded-clients" type="excludedClientsEntity"/>

    <xs:element name="excluded-client" type="excludedClientEntity"/>

    <xs:complexType name="extensionEntity">
        <xs:all>
            <xs:element ref="internal" minOccurs="0"/>
            <xs:element ref="message-log" minOccurs="0"/>
            <xs:element ref="bridges"/>
            <xs:element ref="hmq-hop-count-removal" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="generalInternalEntity">
        <xs:sequence>
            <xs:element ref="option" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="optionEntity">
        <xs:all>
            <xs:element name="key" type="xs:string" minOccurs="0"/>
            <xs:element name="value" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="messageLogEntity">
        <xs:all>
            <xs:element name="enabled" type="xs:boolean"/>
            <xs:element name="log-level" type="xs:string" minOccurs="0"/>
            <xs:element name="mqtt-packets" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="bridgesEntity">
        <xs:sequence>
            <xs:element ref="bridge" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeEntity">
        <xs:all>
            <xs:element name="enabled" type="xs:boolean" default="true" minOccurs="0"/>
            <xs:element name="name" type="routeId" minOccurs="0"/>
            <xs:element ref="remote-broker"/>
            <xs:element ref="topics"/>
            <xs:element ref="loop-prevention" minOccurs="0"/>
            <xs:element ref="internal" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="remoteBrokerEntity">
        <xs:all>
            <xs:element ref="authentication" minOccurs="0"/>
            <xs:element ref="mqtt" minOccurs="0"/>
            <xs:element ref="tls" minOccurs="0"/>
            <xs:element ref="connection"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="authenticationEntity">
        <xs:sequence>
            <xs:element ref="mqtt-simple-authentication"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mqttSimpleAuthenticationEntity">
        <xs:all>
            <xs:element name="username" type="xs:string" minOccurs="0"/>
            <xs:element name="password" type="xs:string" minOccurs="0"/>
            <xs:element name="token" type="xs:string" minOccurs="0"/>
            <xs:element name="client-identifier" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="mqttEntity">
        <xs:all>
            <xs:element name="version" type="xs:string" default="mqttVersion" minOccurs="0"/>
            <xs:element name="clean-start" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="session-expiry" type="xs:int" default="3600" minOccurs="0"/>
            <xs:element name="keep-alive" type="xs:int" default="60" minOccurs="0"/>
            <xs:element ref="flow-control" minOccurs="0"/>
            <xs:element name="always-resubscribe" type="xs:boolean" default="false" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="tlsEntity">
        <xs:all>
            <xs:element name="enabled" type="xs:boolean" minOccurs="0"/>
            <xs:element ref="keystore" minOccurs="0"/>
            <xs:element ref="truststore" minOccurs="0"/>
            <xs:element ref="cipher-suites" minOccurs="0"/>
            <xs:element ref="protocols" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="keystoreEntity">
        <xs:all>
            <xs:element name="path" type="xs:string" minOccurs="0"/>
            <xs:element name="private-key-password" type="xs:string" minOccurs="0"/>
            <xs:element name="password" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="truststoreEntity">
        <xs:all>
            <xs:element name="path" type="xs:string"/>
            <xs:element name="password" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="cipherSuitesEntity">
        <xs:sequence>
            <xs:element name="cipher-suite" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="protocolsEntity">
        <xs:sequence>
            <xs:element name="protocol" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="connectionEntity">
        <xs:all>
            <xs:element ref="static" minOccurs="0"/>
            <xs:element ref="websocket" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="staticConnectionEntity">
        <xs:all>
            <xs:element name="host" type="xs:string" minOccurs="0"/>
            <xs:element name="port" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="websocketEntity">
        <xs:all>
            <xs:element name="enabled" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="server-path" type="xs:string" default="mqtt" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="topicsEntity">
        <xs:sequence>
            <xs:element ref="topic" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="topicEntity">
        <xs:all>
            <xs:element name="filter" type="xs:string"/>
            <xs:element name="exclude" type="xs:string" default="" minOccurs="0"/>
            <xs:element ref="excludes" minOccurs="0"/>
            <xs:element name="destination" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="mode" type="mqttMode" default="PUB" minOccurs="0"/>
            <xs:element name="max-qos" type="xs:int" default="2" minOccurs="0"/>
            <xs:element name="preserve-retained" type="xs:boolean" default="false" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="excludedFiltersEntity">
        <xs:sequence>
            <xs:element name="topic-filter" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeInternalEntity">
        <xs:sequence>
            <xs:element ref="option" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="flowControlEntity">
        <xs:all>
            <xs:element name="send-maximum" type="xs:positiveInteger" minOccurs="0"/>
            <xs:element name="outbound-publish-rate-limit" type="xs:positiveInteger" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="loopPreventionEntity">
        <xs:all>
            <xs:element name="hop-count-limit" type="xs:positiveInteger" minOccurs="0" default="1"/>
            <xs:element name="enabled" type="xs:boolean" minOccurs="0" default="true"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="hopCountRemovalEntity">
        <xs:all>
            <xs:element name="enabled" type="xs:boolean" minOccurs="0" default="false"/>
            <xs:element ref="excluded-clients"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="excludedClientsEntity">
        <xs:sequence>
            <xs:element ref="excluded-client"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="excludedClientEntity">
        <xs:sequence>
            <xs:element name="client-id-pattern" type="xs:string" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="mqttMode">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PUB"/>
            <xs:enumeration value="SUB"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="mqttVersion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="3"/>
            <xs:enumeration value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="routeId">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-z0-9_-]+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-bridge-extension/conf/examples/config-minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<hivemq-bridge-extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:noNamespaceSchemaLocation="config.xsd">
    <bridges>
        <bridge>
            <name>test-bridge</name>
            <remote-broker>
                <connection>
                    <static>
                        <host>localhost</host>
                    </static>
                </connection>
            </remote-broker>
            <topics>
                <topic>
                    <filter>+/+/+/+/machine/data</filter>
                </topic>
            </topics>
        </bridge>
    </bridges>
</hivemq-bridge-extension>

=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-bridge-extension/conf/examples/config-mqtt3.xml
<?xml version="1.0" encoding="UTF-8"?>
<hivemq-bridge-extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:noNamespaceSchemaLocation="config.xsd">
    <bridges>
        <bridge>
            <enabled>true</enabled>
            <name>testbridge</name>
            <remote-broker>
                <mqtt>
                    <version>3</version>
                </mqtt>
                <connection>
                    <static>
                        <host>remote</host>
                        <port>1883</port>
                    </static>
                </connection>
                <authentication>
                    <mqtt-simple-authentication>
                        <username>my-username</username>
                        <password>my-password</password>
                    </mqtt-simple-authentication>
                </authentication>
            </remote-broker>
            <topics>
                <topic>
                    <filter>bridge/topic/test</filter>
                    <mode>PUB</mode>
                </topic>
            </topics>
        </bridge>
    </bridges>
</hivemq-bridge-extension>

=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-bridge-extension/conf/examples/config-enhanced.xml
<?xml version="1.0" encoding="UTF-8"?>
<hivemq-bridge-extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:noNamespaceSchemaLocation="config.xsd">
    <message-log>
        <enabled>true</enabled>
        <log-level>DEBUG</log-level>
        <mqtt-packets>CONNECT, INCOMING-PUBLISH, SUBSCRIBE, OUTGOING-PUBLISH</mqtt-packets>
    </message-log>
    <bridges>
        <bridge>
            <!-- default is true -->
            <enabled>true</enabled>
            <!-- environment variable can be used  i.e. $ENV{HIVEMQ_BRIDGE_NAME} -->
            <name>test-bridge</name>
            <remote-broker>
                <authentication>
                    <mqtt-simple-authentication>
                        <username>myBridgeClient</username>
                        <password>myPassword</password>
                        <token>myToken</token>
                    </mqtt-simple-authentication>
                </authentication>
                <connection>
                    <static>
                        <!-- environment variables can be used  i.e. $ENV{REMOTE_BROKER_HOST} $ENV{REMOTE_BROKER_PORT} -->
                        <host>localhost</host>
                        <port>8883</port>
                    </static>
                </connection>
                <mqtt>
                    <clean-start>true</clean-start>
                    <keep-alive>60</keep-alive>
                    <session-expiry>3600</session-expiry>
                </mqtt>
                <tls>
                    <enabled>true</enabled>
                    <keystore>
                        <path>keystore.jks</path>
                        <password>changeme</password>
                        <private-key-password>changeme</private-key-password>
                    </keystore>
                    <truststore>
                        <path>truststore.jks</path>
                        <password>changeme</password>
                    </truststore>
                    <cipher-suites>
                        <cipher-suite>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384</cipher-suite>
                        <cipher-suite>TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256</cipher-suite>
                        <cipher-suite>TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256</cipher-suite>
                        <cipher-suite>TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384</cipher-suite>
                        <cipher-suite>TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA</cipher-suite>
                        <cipher-suite>TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA</cipher-suite>
                        <cipher-suite>TLS_RSA_WITH_AES_128_GCM_SHA256</cipher-suite>
                        <cipher-suite>TLS_RSA_WITH_AES_128_CBC_SHA</cipher-suite>
                        <cipher-suite>TLS_RSA_WITH_AES_256_CBC_SHA</cipher-suite>
                    </cipher-suites>
                    <protocols>
                        <protocol>TLSv1.2</protocol>
                    </protocols>
                </tls>
            </remote-broker>
            <topics>
                <topic>
                    <filter>+/+/+/+/machine/data</filter>
                    <mode>PUB</mode>
                    <!-- destination will be mytest/original-topic -->
                    <destination>mytest/{#}</destination>
                    <!-- default is false -->
                    <preserve-retained>false</preserve-retained>
                </topic>
                <topic>
                    <filter>+/+/+/+/machine/station</filter>
                    <mode>PUB</mode>
                    <!-- destination will be mytest/original-topic -->
                    <destination>mytest/{#}</destination>
                </topic>
                <topic>
                    <filter>+/+/+/+/machine/error</filter>
                    <mode>PUB</mode>
                    <!-- destination will be mytest/original-topic -->
                    <destination>mytest/{#}</destination>
                </topic>
                <topic>
                    <filter>mytest/+/area/line/cell/machine/station</filter>
                    <mode>SUB</mode>
                    <!-- destination will be original-topic -->
                    <!-- default is false -->
                    <preserve-retained>false</preserve-retained>
                </topic>
            </topics>
        </bridge>
        <bridge>
            <!-- default is true -->
            <enabled>true</enabled>
            <!-- environment variable can be used  i.e. $ENV{HIVEMQ_BRIDGE_NAME} -->
            <name>$ENV{HIVEMQ_BRIDGE_NAME}-cloud</name>
            <remote-broker>
                <authentication>
                    <mqtt-simple-authentication>
                        <username>AUserName</username>
                        <password>APassword</password>
                    </mqtt-simple-authentication>
                </authentication>
                <connection>
                    <static>
                        <!-- environment variables can be used  i.e. $ENV{REMOTE_BROKER_HOST} $ENV{REMOTE_BROKER_PORT} -->
                        <host>someIP.env-1.hivemq.cloud</host>
                        <port>8883</port>
                    </static>
                </connection>
                <mqtt>
                    <clean-start>true</clean-start>
                    <keep-alive>60</keep-alive>
                    <session-expiry>3600</session-expiry>
                </mqtt>
            </remote-broker>
            <topics>
                <topic>
                    <filter>+/+/+/+/machine/data</filter>
                    <mode>PUB</mode>
                    <!-- destination will be mytest/original-topic -->
                    <destination>mytest/{#}</destination>
                </topic>
                <topic>
                    <filter>+/+/+/+/machine/station</filter>
                    <mode>PUB</mode>
                    <!-- exclude specific topics from bridging -->
                    <exclude>test/+/+/+/machine/station</exclude>
                    <!-- destination will be mytest/original-topic -->
                    <destination>mytest/{#}</destination>
                </topic>
                <topic>
                    <filter>mytest/+/area/line/cell/machine/station</filter>
                    <mode>SUB</mode>
                    <!-- destination will be original-topic -->
                </topic>
                <topic>
                    <filter>+/trade/+/+/machine/data</filter>
                    <mode>PUB</mode>
                    <!-- destination will be mytest/trade/+/+... removing level 0 from origin -->
                    <destination>mytest/{1-#}</destination>
                </topic>
                <topic>
                    <filter>+/cell/machine/station/worker/temperature</filter>
                    <mode>SUB</mode>
                    <!-- destination will be "mytest/cell/machine/station" mytest/ + level 1-3 from origin  -->
                    <destination>mytest/{1-3}</destination>
                </topic>
            </topics>
        </bridge>
    </bridges>
</hivemq-bridge-extension>
