=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-mongodb-extension/conf/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="hivemq-mongodb-extension" type="configEntity">
        <xs:key name="mongodb-id">
            <xs:selector xpath="mongodbs/mongodb"/>
            <xs:field xpath="id"/>
        </xs:key>
        <xs:keyref name="mqtt-to-mongodb-id-ref" refer="mongodb-id">
            <xs:selector xpath="mqtt-to-mongodb-routes/mqtt-to-mongodb-route"/>
            <xs:field xpath="mongodb-id"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="configEntity">
        <xs:all>
            <xs:element name="internal" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="option" type="InternalOptionEntity" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="mongodbs">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mongodb" type="MongoDbsEntity" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="mqtt-to-mongodb-routes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mqtt-to-mongodb-route" type="MqttToMongoDbRouteEntity" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="InternalOptionEntity">
        <xs:all>
            <xs:element name="key" type="nonEmptyString"/>
            <xs:element name="value" type="nonEmptyString"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="MongoDbsEntity">
        <xs:sequence>
            <xs:element name="id" type="lowercaseId"/>
            <xs:choice>
                <xs:element name="connection" type="ConnectionEntity"/>
                <xs:element name="connection-string" type="nonEmptyString"/>
            </xs:choice>
            <xs:element name="tls" minOccurs="0">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="enabled" type="xs:boolean" minOccurs="0"/>
                        <xs:element name="keystore" minOccurs="0">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element name="path" type="nonEmptyString"/>
                                    <xs:element name="private-key-password" type="nonEmptyString"/>
                                    <xs:element name="password" type="nonEmptyString"/>
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="truststore" minOccurs="0">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element name="path" type="nonEmptyString"/>
                                    <xs:element name="password" type="nonEmptyString"/>
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="verify-hostname" type="xs:boolean" minOccurs="0"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MqttToMongoDbRouteEntity">
        <xs:all>
            <xs:element name="id" type="lowercaseId"/>
            <xs:element name="mongodb-id" type="xs:IDREF"/>
            <xs:element name="enabled" type="xs:boolean" minOccurs="0"/>
            <xs:element name="database" type="nonEmptyString"/>
            <xs:element name="collection" type="nonEmptyString"/>
            <xs:element name="mqtt-topic-filters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mqtt-topic-filter" type="nonEmptyString" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="processor">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="document-template" type="nonEmptyString"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ConnectionEntity">
        <xs:all>
            <xs:element name="host" type="nonEmptyString"/>
            <xs:element name="port" type="xs:nonNegativeInteger"/>
            <xs:element name="authentication" type="AuthenticationEntity" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="AuthenticationEntity">
        <xs:choice>
            <xs:element name="basic" type="BasicAuthenticationEntity"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="BasicAuthenticationEntity">
        <xs:all>
            <xs:element name="username" type="nonEmptyString"/>
            <xs:element name="password" type="nonEmptyString"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="columnValueEntity">
        <xs:union memberTypes="allowedPlaceholdersEnum allowedPlaceholdersPattern"/>
    </xs:simpleType>

    <xs:simpleType name="allowedPlaceholdersEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mqtt-topic"/>
            <xs:enumeration value="mqtt-payload-utf8"/>
            <xs:enumeration value="mqtt-payload-base64"/>
            <xs:enumeration value="mqtt-qos"/>
            <xs:enumeration value="mqtt-retain"/>
            <xs:enumeration value="mqtt-packet-id"/>
            <xs:enumeration value="mqtt-payload-format-indicator"/>
            <xs:enumeration value="mqtt-response-topic"/>
            <xs:enumeration value="mqtt-correlation-data-utf8"/>
            <xs:enumeration value="mqtt-correlation-data-base64"/>
            <xs:enumeration value="mqtt-user-properties-json"/>
            <xs:enumeration value="timestamp-ms"/>
            <xs:enumeration value="timestamp-iso-8601"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="allowedPlaceholdersPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="mqtt-user-properties\$.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lowercaseId">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-z0-9_\-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== padames/MQTT-Masterclas-hiveMQ/Section 2/resources/hivemq-4.40.1/extensions/hivemq-mongodb-extension/conf/examples/config.xml
<hivemq-mongodb-extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:noNamespaceSchemaLocation="config.xsd">
    <mongodbs>
        <mongodb>
            <id>my-mongodb-id</id>
            <connection>
                <host>my.host.com</host>
                <port>27017</port>
            </connection>
        </mongodb>
    </mongodbs>

    <mqtt-to-mongodb-routes>
        <mqtt-to-mongodb-route>
            <id>my-mqtt-to-mongodb-route</id>
            <mongodb-id>my-mongodb-id</mongodb-id>
            <mqtt-topic-filters>
                <mqtt-topic-filter>#</mqtt-topic-filter>
            </mqtt-topic-filters>
            <collection>my-collection</collection>
            <database>my-database</database>
            <processor>
                <document-template>document-template.json</document-template>
            </processor>
        </mqtt-to-mongodb-route>
    </mqtt-to-mongodb-routes>
</hivemq-mongodb-extension>
